config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  resources :prototypes do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end
  scope module: :prototypes do
    resources :newest, only: :index
    resources :popular, only: :index
    resources :tags, only: [:index, :show]
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype, counter_cache: :comments_count
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :prototype, counter_cache: :likes_count
  belongs_to :user
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :prototype_images
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :prototype_images, allow_destroy: true, reject_if: proc { |attributes| attributes['content'].blank? }
  validates :name, :concept, :catch_copy, presence: true

  acts_as_taggable_on :prototypes # prototype.prototype_list が追加される
  acts_as_taggable            # acts_as_taggable_on :tags のエイリアス

  paginates_per 8

  def liked_user?(user)
    likes.find_by(user_id: user)
  end
end

app/models/prototype_image.rb
class PrototypeImage < ActiveRecord::Base
  belongs_to :prototype
  mount_uploader :content, PrototypeImageUploader
  enum status: %i{main sub}

  validates :status, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, UserImageUploader

  has_many :prototypes
  has_many :likes
  
  has_many :comments
  validates :name, :password, :email, presence: true

  paginates_per 8
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :works, :profile, :avatar, :member])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :works, :profile, :avatar, :member])
  end

  # sign_outしたあとsign_in画面にリダイレクト
  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %(create)
  before_action :set_prototype, only: %(create)

  def create
    @prototype.comments.create(comment_params)
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :user_id, :prototype_id)
  end

  def set_prototype
    @prototype = Prototype.find(params[:prototype_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, only: %(create, destroy)
  before_action :set_prototype, only: %(create, destroy)

  def create
    @prototype = Prototype.find(params[:prototype_id])
    @like = @prototype.likes.create(user_id: current_user.id)
  end

  def destroy
    like = Like.find(params[:id])
    like.destroy
    @prototype = Prototype.find(params[:prototype_id])
  end

  private

  def set_prototype
    @prototype = Prototype.find(params[:prototype_id])
  end
end

app/controllers/prototypes/newest_controller.rb
class Prototypes::NewestController < ApplicationController
  def index
    @prototypes = Prototype.includes(:user).order('created_at DESC').page(params[:page])
    render 'prototypes/index'
  end
end

app/controllers/prototypes/popular_controller.rb
class Prototypes::PopularController < ApplicationController
  def index
    @prototypes = Prototype.includes(:user).order('likes_count DESC').page(params[:page])
    render 'prototypes/index'
  end
end

app/controllers/prototypes/tags_controller.rb
class Prototypes::TagsController < ApplicationController

  def index
     @tags = ActsAsTaggableOn::Tag.most_used
  end

  def show
     @tag = ActsAsTaggableOn::Tag.find(params[:id])
     @prototypes = Prototype.tagged_with(@tag).includes([:user, :tags])
  end

end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_prototype, only: %i(show edit update)

  def index
    @prototypes = Prototype.all.page(params[:page])
  end

  def new
    @prototype = Prototype.new
    @main_content = @prototype.prototype_images.build
    @sub_contents = 2.times { @prototype.prototype_images.build }
  end

  def create
    @prototype = current_user.prototypes.new(prototype_params)
    if @prototype.save
      redirect_to :root, notice: 'New prototype was successfully created'
    else
      redirect_to new_prototype_url, alert: 'New prototype was unsuccessfully created'
    end
  end

  def show
     @like  = @prototype.likes.find_by(user_id: current_user.id)
     @comment = Comment.new(prototype_id: @prototype_id)
     @comments = @prototype.comments.includes(:user)
  end

  def edit
    @main_content = @prototype.prototype_images.first
    @sub_contents = @prototype.prototype_images.sub
  end

  def update
    if @prototype.update(prototype_params)
       redirect_to action: 'show'
    else
       render action: 'edit'
    end
  end

  def destroy
    @prototype = Prototype.find(params[:id])
    @prototype.destroy
    redirect_to :root, notice: "The prototype was successfully deleted"
  end

  private
  def prototype_params
    params.require(:prototype).permit(
    :name,
    :concept,
    :catch_copy,
    :user_id,
    :created_at,
    :likes_count,
    prototype_images_attributes: [:id, :content, :status]).merge(
    tag_list: params[:prototype][:tag])
  end

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :get_user, only: [:show, :edit, :update]

  def show
    @prototypes = @user.prototypes.page(params[:page])
    @proto_count = @user.prototypes.count
  end

  def edit
  end

  def update
    @user.update(update_params)
    redirect_to :root, flash: { success: 'Success update' }
  end

  private
  def get_user
    @user = User.find(params[:id])
  end

  def update_params
    params.require(:user).permit(:name, :emal, :password, :works, :profile, :avatar, :member)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/views/comments/_comment.html.haml
.media
  .media-left
    %img.media-object
    = link_to image_tag(comment.user.avatar,style: 'width: 64px; height: 64px;', alt: '64x64'), user_path(comment.user)
  .media-body
    %h4#top-aligned-media.media-heading
      = comment.user.name
    %p
      = comment.comment

app/views/comments/create.js.haml
$("#comments_count").text("(#{ @prototype.comments_count })");
$("#comments_text").val("");
$("#comments").html("#{ render partial: 'comments/comment', collection: @comments }");
j

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    - if user_signed_in?
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", href: "#", role: "button"}
            #{ current_user.name }
            %span.caret
          %ul.dropdown-menu{role: "menu"}
            %li
              =link_to 'My Page',user_path(current_user)
            %li
              =link_to 'Profile Edit', edit_user_path(current_user)
            %li
              =link_to 'Logout', destroy_user_session_path, method: :delete
        %li
          .btn.btn-primary.navbar-btn
            =link_to 'New Proto',new_prototype_path
    - else
      %ul.nav.navbar-nav.navbar-right
        %li
          .btn.btn-primary.navbar-btn
            =link_to 'GET START',new_user_session_path

app/views/layouts/_messages.html.haml
-flash.each do |key, value|
  %div{class: "alert alert-#{key}"}
    = link_to 'x', '#', data: { dismiss: 'alert' }, class: 'close'
    %ul
      %li
        = value

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    .container
    = render "layouts/messages"
    = yield
    = render "layouts/footer"

app/views/likes/_like.html.haml
- if user_signed_in?
  - if prototype.liked_user?(current_user)
    = button_to prototype_like_path(id: like.id, prototype_id: prototype.id), method: :delete, id: "like_buttons",remote: true, class: 'btn btn-default' do
      = image_tag("icon_heart_red.svg")
      Like
      %span#like_buttons.num
        = prototype.likes_count
  -else
    = button_to prototype_likes_path(prototype), class: "btn btn-default", id: "like_buttons", remote: true do
      = image_tag("icon_heart.svg")
      Like
      %span#like_buttons.num
        = prototype.likes_count
- else
  %button.btn.btn-default.btn--like
    = image_tag("icon_heart.svg")
    Like
    %span#like_buttons.num
      = prototype.likes_count

app/views/likes/create.js.haml
$("#like_buttons").html("#{ j render partial: 'likes/like', locals: { prototype: @prototype, like: @like }}");

app/views/likes/destroy.js.haml
$("#like_buttons").html("#{ j render partial: 'likes/like', locals: { prototype: @prototype, like: @like }}");

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    = link_to image_tag(prototype.prototype_images.first.content), prototype_path(prototype.id)
    .caption
      %h3
        = prototype.name
      .proto-meta
        .proto-user
          = link_to "by #{prototype.user.name}", user_path(prototype.user.id)
        .proto-posted
          = prototype.created_at.strftime('%m/%d')
      %ul.proto-tag-list.list-inline
        %li
          - prototype.tags.each do |tag|
            %li
              = link_to "#{tag.name}", tag_path(tag), class: "btn btn-default"

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :name, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          .cover-image-upload.js-image-preview
            = f.fields_for :prototype_images, @main_content do |main_image|
              .js-image-upload
                = image_tag(main_image.object.image, class: 'img-responsive')
                = main_image.file_field :image
                = main_image.hidden_field :status, value: 'main'
        .col-md-12
          %ul.proto-sub-list.list-group
            = f.fields_for :prototype_images, @sub_contents do |sub_image|
              %li.list-group-item.col-md-4
                .image-upload.js-image-preview
                  = image_tag(sub_image.object.image, class: 'img-responsive')
                  = sub_image.file_field :image
                  = sub_image.hidden_field :status, value: 'sub'
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
      .row.text-center.proto-btn
        = f.submit 'UPDATE', id: 'button', class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          = link_to "Popular PROTO", popular_index_path, class: "btn btn-primary navbar-btn"
        %li{role: "presentation"}
          = link_to "Newest PROTO", newest_index_path, class: "btn btn-primary navbar-btn"
      = link_to "VIEW TAGS", tags_path, class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  %ul.pagination
    = paginate(@prototypes)

app/views/prototypes/new.html.haml
.container.proto-new{action: ""}
  = form_for @prototype do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          .proto-new-title
            = f.text_field :name ,placeholder: "Title"
      .row
        .col-md-12
          .cover-image-upload.js-image-preview
            = f.fields_for :prototype_images, @main_content do |prototype_image|
              .js-image-upload
                = image_tag(prototype_image.object.content, class: 'img-responsive')
                = prototype_image.file_field :content
                = prototype_image.hidden_field :status, value: "main"
        .col-md-12
          %ul.proto-sub-list.list-group
            = f.fields_for :prototype_images, @sub_contents do |prototype_image|
              %li.list-group-item.col-md-4
                .image-upload.js-image-preview
                  = image_tag(prototype_image.object.content, class: 'img-responsive')
                  = prototype_image.file_field :content
                  = prototype_image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          = f.text_field :catch_copy, placeholder: "Catch Copy"
        .col-md-12
          = f.text_area :concept, placeholder: "Concept", cols: "30", rows: "4"
        .col-md-12
          %h4 Tag List
          .row
            .col-md-3
              = text_field_tag "prototype[tag][]", "", placeholder: "Web Design"
            .col-md-3
              = text_field_tag "prototype[tag][]", "", placeholder: "UI"
            .col-md-3
              = text_field_tag "prototype[tag][]", "", placeholder: "Application"
    .row.text-center.proto-btn
      = f.submit "Post!", id: "up_btn", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag(@prototype.user.avatar, alt: "avatar", class: "media-object", style: "width: 64px; height: 64px;")
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.name
          .proto-user
            = link_to "by #{ @prototype.user.name }", user_path(@prototype.user)
            %spam.degree = #{ @prototype.user.member }

    .col-md-6.text-right#like_buttons
      = render partial: 'likes/like', locals: { prototype: @prototype, like: @like }
    .col-md-6.text-right
      .extra-button
        - if user_signed_in? && (@prototype.user_id == current_user.id)
          .btn.btn-default.navbar-btn
            = link_to "Edit", edit_prototype_path(@prototype)

          .btn.btn-default.navbar-btn
            = link_to "Delete", prototype_path(@prototype), method: :delete

  .row
    .col-md-9
      = image_tag(@prototype.prototype_images.first.image, class: 'img-responsive')
    .col-md-3
      %ul.proto-sub-list.list-group
      - @prototype.prototype_images.sub.each do |sub_image|
        %li.list-group-item
          = image_tag(sub_image.image, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
      = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p
      = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        = render partial: "prototypes/tags/tag", collection: @prototype.tags
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span#comments.num
        = "(#{ @prototype.comments_count })"
    .col-md-8
      #js-comments
        = render partial: 'comments/comment', collection: @comments
      .form-inline
        - if user_signed_in?
          = form_for [@prototype,@comment], remote: true do |f|
            = f.hidden_field :user_id, value: current_user.id
            = f.hidden_field :prototype_id, value: @prototype.id
            %h4 Write a comment
            .row
              .form-group.col-md-10
                = f.text_area :comment, placeholder: "Your comments", class: "form-control", rows: "3"
              .form-group.col-md-2
                = f.submit "Comment", class: 'button btn btn-primary'

app/views/prototypes/tags/_tag.html.haml
.col-sm-4.col-sm-3
  = link_to tag_path(tag.id), class: 'tag thumbnail' do
    .tag-name
      = tag.name
    .tag-project
      = "#{tag.taggings_count} projects"

app/views/prototypes/tags/index.html.haml
.container
  .row
    .tag_list
      %h2 Tag List
      = render partial: 'tag', collection: @tags

app/views/prototypes/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          = link_to "Popular PROTO", popular_index_path, class: "btn btn-primary navbar-btn"
        %li{role: "presentation"}
          = link_to "Newest PROTO", newest_index_path, class: "btn btn-primary navbar-btn"
      = link_to "VIEW TAGS", tags_path, class: "btn btn-default col-lg-1"

.container
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes

app/views/users/edit.html.haml
.container.user-new
  = form_for @user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit Profile
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :name, placeholder: "Username", autofocus: true, required: true
            .user-image.col-md-2.js-image-preview{ style: "background-image: url(#{ current_user.avatar });" }
              = f.button 'Change Image(), class:"btn btn-primary"
              .js-preview-image
                = f.file_field :avatar
          .user-email
            = f.email_field :email, placeholder: "E-Mail", required: true
          .user-password
            = f.password_field :password, placeholder: "Password", required: true
        .col-md-12
          %h4 Member of
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :member, placeholder: "Member", required: true
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, placeholder: "profile", required: true
          %h4 Works
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :works, placeholder: "Works", cols: "30", rows: "4"
      .row.text-center.user-btn
        = f.submit 'SAVE', class: "btn btn-lg btn-primary btn-block"

app/views/users/index.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        %a{:href => "#"}
          %img.media-object{:alt => "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", :src => "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", :style => "width: 64px; height: 64px;"}/
      .media-body
        %h4#top-aligned-media.media-heading
          Top aligned media
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree we-b inc. Designer
        .row
          .col-md-6
            %h4 Profile
            %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          .col-md-6
            %h4 Works
            %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
.container.proto-list
  .row
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
                
.text-center
  %ul.pagination
    %li.disabled
      %a{"aria-label" => "Previous", :href => "#"}
        %span{"aria-hidden" => "true"} «
    %li.active
      %a{:href => "#"}
        1
        %span.sr-only (current)
    %li
      %a{:href => "#"} 2
    %li
      %a{:href => "#"} 3
    %li
      %a{:href => "#"} 4
    %li
      %a{:href => "#"} 5
    %li
      %a{"aria-label" => "Next", :href => "#"}
        %span{"aria-hidden" => "true"} »

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        %a{href: "#"}
          = image_tag(@user.avatar, alt: ' avatar', class: "media-object", style: "width: 64px; height: 64px;")
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.name
          %span.label.label-default.project-number
            = @proto_count
            %i Projects
        .proto-user
          %span.degree #{ @user.member }
        .row
          .col-md-6
            %h4 Profile
            %p
            = @user.profile
          .col-md-6
            %h4 Works
            %p
            = @user.works
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  %ul.pagination
    = paginate(@prototypes)